### Send PUT request with json body
#DELETE http://localhost:9200/twitter-index

PUT http://localhost:9200/twitter-index
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "userId": {
        "type": "long"
      },
      "id": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "createdAt": {
        "type": "date",
        "format":"YYYY-MM-DD'T'HH:mm:ssZ"
      },
      "text": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  }
}

