#GET http://localhost:9200/twitter-index/_search
#GET http://localhost:9200/twitter-index/_search?q=id:3029825665538976457

GET http://localhost:9200/twitter-index/_search
Content-Type: application/json

{
    "size": 250,
     "from": 0
}


